<?php
/**
 * User management helpers.
 *
 * @package migration_freeze_webspark
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

function mfw_get_site_users() { return get_users( array( 'blog_id' => get_current_blog_id(), 'fields' => 'all' ) ); }
function mfw_user_is_migration_team_member( $user ) { if ( ! ( $user instanceof WP_User ) ) { return false; } return in_array( mfw_normalize_username( $user->user_login ), mfw_get_migration_assistants(), true ); }
function mfw_is_multisite_context() { return is_multisite(); }
function mfw_ensure_migration_team_users_exist() { $created = array(); foreach ( mfw_get_migration_assistants() as $username ) { $existing = get_user_by( 'login', $username ); if ( $existing instanceof WP_User ) { continue; } $email = $username . '@asu.edu'; $random_password = wp_generate_password( 32, true, true ); $user_id = wp_create_user( $username, $random_password, $email ); if ( ! is_wp_error( $user_id ) ) { $created[] = $username; } } return $created; }
function mfw_apply_state_changes( $state = null ) { $state = $state ? sanitize_key( $state ) : mfw_get_site_state(); switch ( $state ) { case MFW_STATE_NORMAL: return array( 'state' => $state, 'changes_made' => false, 'created' => array(), 'promoted' => array(), 'demoted' => array(), 'removed' => array(), 'missing' => array(), 'message' => __( 'No migration activity is scheduled for this site.', 'migration-freeze-webspark' ) ); case MFW_STATE_ACTIVE: return mfw_apply_active_state(); case MFW_STATE_UAT_COMPLETE: return mfw_apply_uat_complete_state(); case MFW_STATE_DECOMMISSIONED: return mfw_apply_decommissioned_state(); case MFW_STATE_PENDING: case MFW_STATE_COMPLETE: default: return array( 'state' => $state, 'changes_made' => false, 'created' => array(), 'promoted' => array(), 'demoted' => array(), 'removed' => array(), 'missing' => array(), 'message' => __( 'No user changes were applied for this state.', 'migration-freeze-webspark' ) ); } }
function mfw_assign_user_role( $user, $role ) { if ( ! ( $user instanceof WP_User ) ) { return; } $blog_id = get_current_blog_id(); if ( mfw_is_multisite_context() && function_exists( 'add_user_to_blog' ) ) { add_user_to_blog( $blog_id, $user->ID, $role ); return; } $user_obj = new WP_User( $user->ID ); $user_obj->set_role( $role ); }
function mfw_remove_user_site_roles( $user ) { if ( ! ( $user instanceof WP_User ) ) { return false; } $blog_id = get_current_blog_id(); if ( mfw_is_multisite_context() && function_exists( 'remove_user_from_blog' ) ) { return (bool) remove_user_from_blog( $user->ID, $blog_id ); } global $wpdb; $cap_key = $wpdb->get_blog_prefix( $blog_id ) . 'capabilities'; update_user_meta( $user->ID, $cap_key, array() ); clean_user_cache( $user->ID ); return true; }
function mfw_apply_active_state() { $current_user = get_current_user_id(); $created = mfw_ensure_migration_team_users_exist(); $promoted = array(); $demoted = array(); $missing = array(); $team_lookup = array_flip( mfw_get_migration_assistants() ); foreach ( mfw_get_migration_assistants() as $username ) { $user = get_user_by( 'login', $username ); if ( ! ( $user instanceof WP_User ) ) { $missing[] = $username; continue; } mfw_assign_user_role( $user, 'administrator' ); $promoted[] = $username; } foreach ( mfw_get_site_users() as $user ) { if ( (int) $user->ID === (int) $current_user ) { continue; } $username = mfw_normalize_username( $user->user_login ); if ( isset( $team_lookup[ $username ] ) ) { continue; } $user_obj = new WP_User( $user->ID ); $roles = (array) $user_obj->roles; if ( in_array( 'subscriber', $roles, true ) && 1 === count( $roles ) ) { continue; } $user_obj->set_role( 'subscriber' ); $demoted[] = $username; } return array( 'state' => MFW_STATE_ACTIVE, 'changes_made' => true, 'created' => $created, 'promoted' => $promoted, 'demoted' => $demoted, 'removed' => array(), 'missing' => $missing, 'message' => __( 'Migration team promotion and subscriber demotion were applied.', 'migration-freeze-webspark' ) ); }
function mfw_apply_uat_complete_state() { $current_user = get_current_user_id(); $removed = array(); foreach ( mfw_get_migration_assistants() as $username ) { $user = get_user_by( 'login', $username ); if ( ! ( $user instanceof WP_User ) ) { continue; } if ( (int) $user->ID === (int) $current_user ) { continue; } if ( mfw_remove_user_site_roles( $user ) ) { $removed[] = $username; } } return array( 'state' => MFW_STATE_UAT_COMPLETE, 'changes_made' => true, 'created' => array(), 'promoted' => array(), 'demoted' => array(), 'removed' => $removed, 'missing' => array(), 'message' => __( 'Migration team members were removed from the site.', 'migration-freeze-webspark' ) ); }
function mfw_apply_decommissioned_state() { $current_user = get_current_user_id(); $removed = array(); foreach ( mfw_get_site_users() as $user ) { if ( (int) $user->ID === (int) $current_user ) { continue; } if ( mfw_remove_user_site_roles( $user ) ) { $removed[] = mfw_normalize_username( $user->user_login ); } } if ( ! mfw_is_multisite_context() ) { return array( 'state' => MFW_STATE_DECOMMISSIONED, 'changes_made' => true, 'created' => array(), 'promoted' => array(), 'demoted' => array(), 'removed' => $removed, 'missing' => array(), 'message' => __( 'All other users were stripped of the current site role on this single-site install.', 'migration-freeze-webspark' ) ); } return array( 'state' => MFW_STATE_DECOMMISSIONED, 'changes_made' => true, 'created' => array(), 'promoted' => array(), 'demoted' => array(), 'removed' => $removed, 'missing' => array(), 'message' => __( 'All site role assignments except the current operator were removed from the site.', 'migration-freeze-webspark' ) ); }
